version: '3'

services:
  app:
    image: gtrows/distributor-order-system:latest
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/orderSystemDB
    volumes:
      - /Users/aciro/keystore.p12:/app/keystore.p12
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
